name: Deploy Release APK to Firebase App Distribution

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install Dependencies
        run: flutter pub get && flutter build apk --release

      - name: Deploy to Firebase using Gradle
        run: cd android && ./gradlew assembleRelease appDistributionUploadRelease

